// aprendiendo-vue/src/components/Pelicula.vue
<template>

    <article class="article-item">
      <div class="img-wrap">
        <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" class="image-wrap" />
      </div>
      <h2>{{pelicula.title}}</h2>
      <span
        class="date"
        :class="{
            yeargreen: pelicula.year >= 2015,
            yearred: pelicula.year < 2015
        }"
      >{{pelicula.year}}</span>
      <a href="#">Leer más</a>

      <input type="button" value="Marcar como favoita" @click="pasarFavpritaAlPadre(pelicula)"/>

      <div class="clearfix"></div>
    </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ['pelicula'],
  methods: {
    pasarFavpritaAlPadre(pelicula){
      this.$emit('favorita', pelicula);
    }
  }
};
</script>

<style>
</style>

// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula.model';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {


  @Input() pelicula: Pelicula;
  @Output() MarcarFavorita =  new EventEmitter();
  constructor() { }

  ngOnInit() {
  }

  seleccionar(event, pelicula){
    this.MarcarFavorita.emit({
      pelicula: pelicula
    });
  }

}

<article class="article-item" >
    <div class="img-wrap">
        <img src="{{pelicula.image}}" alt="Paisaje" class="image-wrap">
    </div>
    <h2>{{i}}. {{pelicula.title}}</h2>
    <span [ngClass]="{
        'year-green': pelicula.year > 2016, 
        'year-red': pelicula.year <= 2016}">
        {{pelicula.year}}
    </span>
    <a href="#">Leer más</a>
    <button (click)="seleccionar($event, pelicula)">
        Seleccionar como favorita
    </button>

    <div class="clearfix"></div>
</article>
